# Generated by Django 4.2.4 on 2024-11-15 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='asset_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('bond', 'Bond'), ('etf', 'ETF')], max_length=10),
        ),
        migrations.AlterField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investmentanalysis',
            name='aggressive_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='investmentanalysis',
            name='conservative_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='investmentanalysis',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
