# Generated by Django 4.2.4 on 2024-11-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='open_price',
        ),
    ]
