# Generated by Django 4.2.4 on 2024-11-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_remove_stock_open_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='close_price',
            new_name='open_price',
        ),
    ]
