# Generated by Django 4.2.4 on 2024-11-25 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='interests',
            new_name='my_investor_type',
        ),
    ]
