# Generated by Django 4.2.4 on 2024-11-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_co_no', models.CharField(max_length=100)),
                ('join_way', models.CharField(default='', max_length=100, null=True)),
                ('max_limit', models.CharField(default='', max_length=100, null=True)),
                ('mtrt_int', models.CharField(max_length=100, null=True)),
                ('join_member', models.CharField(default='', max_length=100, null=True)),
                ('etc_note', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_co_no', models.CharField(max_length=100)),
                ('join_way', models.CharField(default='', max_length=100, null=True)),
                ('max_limit', models.CharField(default='', max_length=100, null=True)),
                ('mtrt_int', models.CharField(default='', max_length=100, null=True)),
                ('join_member', models.CharField(default='', max_length=100, null=True)),
                ('etc_note', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
    ]
