# Generated by Django 4.2.4 on 2024-11-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fndTp', models.CharField(max_length=100)),
                ('prdClsfCd', models.CharField(max_length=100)),
                ('fndNm', models.CharField(max_length=100)),
            ],
        ),
    ]
