# Generated by Django 4.2.4 on 2024-11-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproduct',
            name='etc_note',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='join_member',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='max_limit',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='mtrt_int',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='etc_note',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='join_member',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='max_limit',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='mtrt_int',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
