# Generated by Django 4.2.4 on 2024-11-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_depositproduct_etc_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproduct',
            name='join_way',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='join_way',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='mtrt_int',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
