# Generated by Django 4.2.4 on 2024-11-25 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_fundproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundproduct',
            old_name='prdClsfCd',
            new_name='asoStdCd',
        ),
    ]
